/**
 * @file tags.js
 * @description Capability tags for models. Keys are the exact model IDs used in
 * sources.js provider entries (not deduplicated across providers, matching the
 * convention in scores.js). Tags are restricted to TAG_VOCABULARY.
 */

import { resolveAliasedModelId } from './sources.js'

export const TAG_VOCABULARY = ['coding', 'reasoning', 'general', 'fast', 'agentic']

export const MODEL_TAGS = {
  'arcee-ai/trinity-large-preview': ['general'],
  'bytedance/seed-oss-36b-instruct': ['general'],
  'claude-haiku-4.5': ['fast', 'general'],
  'claude-sonnet-4.5': ['coding', 'general'],
  'codestral-latest': ['coding'],
  'corethink:free': ['reasoning'],
  'deepseek-ai/deepseek-r1-distill-llama-8b': ['reasoning', 'fast'],
  'deepseek-ai/deepseek-r1-distill-qwen-14b': ['reasoning'],
  'deepseek-ai/deepseek-r1-distill-qwen-32b': ['reasoning'],
  'deepseek-ai/deepseek-r1-distill-qwen-7b': ['reasoning', 'fast'],
  'deepseek-ai/deepseek-v3.1': ['general', 'agentic'],
  'deepseek-ai/deepseek-v3.1-terminus': ['general', 'agentic'],
  'deepseek-ai/deepseek-v3.2': ['general', 'agentic', 'coding'],
  'deepseek-r1-distill-llama-70b': ['reasoning'],
  'deepseek/deepseek-r1-0528:free': ['reasoning'],
  'devstral-2-123b-instruct-2512': ['coding'],
  'gemma-3-12b-it': ['general', 'fast'],
  'gemma-3-27b-it': ['general'],
  'gemma-3-4b-it': ['general', 'fast'],
  'giga-potato-thinking:free': ['reasoning'],
  'google/gemma-2-9b-it': ['general', 'fast'],
  'gpt-oss-120b': ['general'],
  'ibm/granite-34b-code-instruct': ['coding'],
  'igenius/colosseum_355b_instruct_16k': ['general'],
  'llama-3.1-8b-instant': ['fast', 'general'],
  'llama-3.3-70b-instruct': ['general'],
  'llama-3.3-70b-versatile': ['general'],
  'llama3.1-8b': ['fast', 'general'],
  'meta-llama/llama-3.3-70b-instruct:free': ['general'],
  'meta-llama/llama-4-maverick-17b-128e-preview': ['general'],
  'meta-llama/llama-4-scout-17b-16e-preview': ['general'],
  'meta/llama-3.1-405b-instruct': ['general'],
  'meta/llama-3.3-70b-instruct': ['general'],
  'meta/llama-4-maverick-17b-128e-instruct': ['general'],
  'meta/llama-4-scout-17b-16e-instruct': ['general'],
  'microsoft/phi-3.5-mini-instruct': ['fast', 'general'],
  'microsoft/phi-4-mini-instruct': ['fast', 'general'],
  'minimax/minimax-m2.5:free': ['agentic', 'general', 'coding'],
  'minimaxai/minimax-m2': ['agentic', 'general'],
  'minimaxai/minimax-m2.1': ['agentic', 'general'],
  'minimaxai/minimax-m3': ['agentic', 'general'],
  'mistral-small-3.2-24b-instruct-2506': ['general'],
  'mistralai/devstral-2-123b-instruct-2512': ['coding'],
  'mistralai/magistral-small-2506': ['reasoning'],
  'mistralai/ministral-14b-instruct-2512': ['fast', 'general'],
  'mistralai/mistral-large-3-675b-instruct-2512': ['general'],
  'mistralai/mistral-medium-3-instruct': ['general'],
  'mistralai/mixtral-8x22b-instruct-v0.1': ['general'],
  'moonshotai/kimi-k2-instruct': ['agentic', 'coding', 'general'],
  'moonshotai/kimi-k2-thinking': ['reasoning', 'agentic'],
  'moonshotai/kimi-k2.5': ['agentic', 'coding', 'general'],
  'moonshotai/kimi-k2.7-code': ['coding'],
  'nvidia/llama-3.1-nemotron-ultra-253b-v1': ['general'],
  'nvidia/llama-3.3-nemotron-super-49b-v1.5': ['general'],
  'nvidia/nemotron-3-nano-30b-a3b': ['fast', 'general'],
  'nvidia/nemotron-3-nano-30b-a3b:free': ['fast', 'general'],
  'nvidia/nemotron-3-ultra-550b-a55b': ['general'],
  'openai/gpt-oss-120b': ['general'],
  'openai/gpt-oss-120b:free': ['general'],
  'openai/gpt-oss-20b': ['fast', 'general'],
  'openai/gpt-oss-20b:free': ['fast', 'general'],
  'qwen-3-235b-a22b-instruct-2507': ['general'],
  'qwen-qwq-32b': ['reasoning'],
  'qwen/qwen2.5-coder-32b-instruct': ['coding'],
  'qwen/qwen3-235b-a22b': ['general'],
  'qwen/qwen3-32b': ['general'],
  'qwen/qwen3-coder-480b-a35b-instruct': ['coding'],
  'qwen/qwen3-coder:free': ['coding'],
  'qwen/qwen3-next-80b-a3b-instruct': ['general'],
  'qwen/qwen3-next-80b-a3b-instruct:free': ['general'],
  'qwen/qwen3-next-80b-a3b-thinking': ['reasoning'],
  'qwen/qwen3.5-397b-a17b': ['general', 'coding'],
  'qwen/qwq-32b': ['reasoning'],
  'qwen3-235b-a22b-instruct-2507': ['general'],
  'qwen3-coder-30b-a3b-instruct': ['coding'],
  'stepfun-ai/step-3.5-flash': ['fast', 'general'],
  'stepfun-ai/step-3.7-flash': ['fast', 'general'],
  'stepfun/step-3.5-flash:free': ['fast', 'general'],
  'stockmark/stockmark-2-100b-instruct': ['general'],
  'xiaomi/mimo-v2-omni:free': ['general'],
  'xiaomi/mimo-v2-pro:free': ['general'],
  'z-ai/glm-5.2': ['agentic', 'coding', 'general'],
  'z-ai/glm4.7': ['agentic', 'coding', 'general'],
  'zai-glm-4.7': ['agentic', 'coding', 'general'],
  'z-ai/glm5': ['agentic', 'coding', 'general'],
}

export function getModelTags(modelId) {
  const raw = typeof modelId === 'string' ? modelId.trim() : ''
  if (!raw) return []
  const resolved = resolveAliasedModelId(raw)
  return MODEL_TAGS[raw] || MODEL_TAGS[resolved] || []
}
